# Generated by Django 2.1.7 on 2019-03-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190306_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Phone'),
        ),
    ]
